/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lafo.view.PopUp.Barang;

/**
 *
 * @author Hp
 */
public class PopUpTambahBarang extends javax.swing.JFrame {

    /**
     * Creates new form PopUpTambahBarang
     */
    public PopUpTambahBarang() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel_kodebarang = new javax.swing.JLabel();
        jTextField_kodebarang = new javax.swing.JTextField();
        jLabel_namabarang = new javax.swing.JLabel();
        jTextField_namabarang = new javax.swing.JTextField();
        jLabel_kategoribarang = new javax.swing.JLabel();
        jTextField_kategoribarang = new javax.swing.JTextField();
        jLabel_satuan = new javax.swing.JLabel();
        jComboBox_satuan = new javax.swing.JComboBox<>();
        jButton_selesai = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel_kodebarang.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel_kodebarang.setText("Kode Barang");

        jTextField_kodebarang.setBackground(new java.awt.Color(146, 147, 147));
        jTextField_kodebarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_kodebarangActionPerformed(evt);
            }
        });

        jLabel_namabarang.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel_namabarang.setText("Nama Barang");

        jTextField_namabarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_namabarangActionPerformed(evt);
            }
        });

        jLabel_kategoribarang.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel_kategoribarang.setText("Kategori Barang");

        jTextField_kategoribarang.setBackground(new java.awt.Color(146, 147, 147));
        jTextField_kategoribarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_kategoribarangActionPerformed(evt);
            }
        });

        jLabel_satuan.setFont(new java.awt.Font("Tahoma", 1, 27)); // NOI18N
        jLabel_satuan.setText("Satuan");

        jComboBox_satuan.setEditable(true);
        jComboBox_satuan.setFont(new java.awt.Font("Tahoma", 0, 27)); // NOI18N
        jComboBox_satuan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman" }));
        jComboBox_satuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_satuanActionPerformed(evt);
            }
        });

        jButton_selesai.setBackground(new java.awt.Color(241, 102, 52));
        jButton_selesai.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton_selesai.setForeground(new java.awt.Color(255, 255, 255));
        jButton_selesai.setText("SIMPAN");
        jButton_selesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_selesaiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel_satuan)
                    .addComponent(jTextField_kategoribarang)
                    .addComponent(jLabel_kategoribarang)
                    .addComponent(jLabel_namabarang)
                    .addComponent(jTextField_namabarang)
                    .addComponent(jLabel_kodebarang)
                    .addComponent(jTextField_kodebarang)
                    .addComponent(jComboBox_satuan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_selesai, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel_kodebarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_kodebarang, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_namabarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_namabarang, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_kategoribarang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox_satuan, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel_satuan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField_kategoribarang, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jButton_selesai, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_kodebarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_kodebarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_kodebarangActionPerformed

    private void jTextField_namabarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_namabarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_namabarangActionPerformed

    private void jTextField_kategoribarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_kategoribarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_kategoribarangActionPerformed

    private void jComboBox_satuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_satuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_satuanActionPerformed

    private void jButton_selesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_selesaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_selesaiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PopUpTambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PopUpTambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PopUpTambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PopUpTambahBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PopUpTambahBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_selesai;
    private javax.swing.JComboBox<String> jComboBox_satuan;
    private javax.swing.JLabel jLabel_kategoribarang;
    private javax.swing.JLabel jLabel_kodebarang;
    private javax.swing.JLabel jLabel_namabarang;
    private javax.swing.JLabel jLabel_satuan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField_kategoribarang;
    private javax.swing.JTextField jTextField_kodebarang;
    private javax.swing.JTextField jTextField_namabarang;
    // End of variables declaration//GEN-END:variables
}
