/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lafo;

/**
 *
 * @author mahmu
 */
public class MainJframe extends javax.swing.JFrame {

    /**
     * Creates new form Kasir
     */
    public MainJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_atas = new javax.swing.JPanel();
        LabelNamaToko = new javax.swing.JLabel();
        LabelNamaUser = new javax.swing.JLabel();
        LabelJabatanUser = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        panelNavigasiBar = new javax.swing.JPanel();
        jLabelLogoTransaksi = new javax.swing.JLabel();
        jLabelManajemenData = new javax.swing.JLabel();
        jLabelLaporan = new javax.swing.JLabel();
        jLabelUsesrs = new javax.swing.JLabel();
        jLabelLogOut = new javax.swing.JLabel();
        panel_tengah = new javax.swing.JPanel();
        ManajemenData = new javax.swing.JPanel();
        Navigasi = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        ContainerConten = new javax.swing.JPanel();
        DataBarang = new javax.swing.JPanel();
        DataSuplier = new javax.swing.JPanel();
        DataKategori = new javax.swing.JPanel();
        Laporan = new javax.swing.JPanel();
        Setting = new javax.swing.JPanel();
        transaksi = new javax.swing.JPanel();
        JPanelLogo = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1, 982));

        panel_atas.setBackground(new java.awt.Color(241, 102, 52));
        panel_atas.setPreferredSize(new java.awt.Dimension(1280, 76));

        LabelNamaToko.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelNamaToko.setForeground(new java.awt.Color(255, 255, 255));
        LabelNamaToko.setText("CAFE LAFO");

        LabelNamaUser.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        LabelNamaUser.setForeground(new java.awt.Color(255, 255, 255));
        LabelNamaUser.setText("Dwi Nafis Mahardika");

        LabelJabatanUser.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelJabatanUser.setForeground(new java.awt.Color(255, 255, 255));
        LabelJabatanUser.setText("Admin");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icon/user.png"))); // NOI18N
        jLabel7.setText("jLabel7");
        jLabel7.setPreferredSize(new java.awt.Dimension(36, 36));

        javax.swing.GroupLayout panel_atasLayout = new javax.swing.GroupLayout(panel_atas);
        panel_atas.setLayout(panel_atasLayout);
        panel_atasLayout.setHorizontalGroup(
            panel_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_atasLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(LabelNamaToko)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panel_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNamaUser)
                    .addComponent(LabelJabatanUser))
                .addGap(38, 38, 38))
        );
        panel_atasLayout.setVerticalGroup(
            panel_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_atasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panel_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_atasLayout.createSequentialGroup()
                        .addComponent(LabelNamaUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelJabatanUser))
                    .addGroup(panel_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabelNamaToko)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelNavigasiBar.setBackground(new java.awt.Color(42, 48, 48));
        panelNavigasiBar.setPreferredSize(new java.awt.Dimension(106, 699));
        panelNavigasiBar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                panelNavigasiBarComponentMoved(evt);
            }
        });

        jLabelLogoTransaksi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icon/airplay.png"))); // NOI18N
        jLabelLogoTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLogoTransaksiMouseClicked(evt);
            }
        });

        jLabelManajemenData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icon/box.png"))); // NOI18N
        jLabelManajemenData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelManajemenDataMouseClicked(evt);
            }
        });

        jLabelLaporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icon/repeat.png"))); // NOI18N
        jLabelLaporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelLaporanMouseClicked(evt);
            }
        });

        jLabelUsesrs.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icon/users.png"))); // NOI18N
        jLabelUsesrs.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelUsesrsMouseClicked(evt);
            }
        });

        jLabelLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icon/log-out.png"))); // NOI18N

        javax.swing.GroupLayout panelNavigasiBarLayout = new javax.swing.GroupLayout(panelNavigasiBar);
        panelNavigasiBar.setLayout(panelNavigasiBarLayout);
        panelNavigasiBarLayout.setHorizontalGroup(
            panelNavigasiBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavigasiBarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelLogOut)
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelNavigasiBarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelNavigasiBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelNavigasiBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabelManajemenData)
                        .addComponent(jLabelLogoTransaksi))
                    .addGroup(panelNavigasiBarLayout.createSequentialGroup()
                        .addGroup(panelNavigasiBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelUsesrs)
                            .addComponent(jLabelLaporan))
                        .addGap(1, 1, 1)))
                .addGap(27, 27, 27))
        );
        panelNavigasiBarLayout.setVerticalGroup(
            panelNavigasiBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavigasiBarLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jLabelLogoTransaksi)
                .addGap(40, 40, 40)
                .addComponent(jLabelManajemenData)
                .addGap(45, 45, 45)
                .addComponent(jLabelLaporan)
                .addGap(37, 37, 37)
                .addComponent(jLabelUsesrs)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLogOut)
                .addGap(33, 33, 33))
        );

        panel_tengah.setPreferredSize(new java.awt.Dimension(1410, 699));
        panel_tengah.setLayout(new java.awt.CardLayout());

        ManajemenData.setBackground(new java.awt.Color(255, 255, 204));

        Navigasi.setPreferredSize(new java.awt.Dimension(1420, 175));

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("jButton2");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("jButton3");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout NavigasiLayout = new javax.swing.GroupLayout(Navigasi);
        Navigasi.setLayout(NavigasiLayout);
        NavigasiLayout.setHorizontalGroup(
            NavigasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigasiLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jButton1)
                .addGap(117, 117, 117)
                .addComponent(jButton2)
                .addGap(121, 121, 121)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        NavigasiLayout.setVerticalGroup(
            NavigasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigasiLayout.createSequentialGroup()
                .addContainerGap(81, Short.MAX_VALUE)
                .addGroup(NavigasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(71, 71, 71))
        );

        ContainerConten.setBackground(new java.awt.Color(204, 255, 204));
        ContainerConten.setPreferredSize(new java.awt.Dimension(1420, 731));
        ContainerConten.setLayout(new java.awt.CardLayout());

        DataBarang.setBackground(new java.awt.Color(0, 153, 153));

        javax.swing.GroupLayout DataBarangLayout = new javax.swing.GroupLayout(DataBarang);
        DataBarang.setLayout(DataBarangLayout);
        DataBarangLayout.setHorizontalGroup(
            DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1420, Short.MAX_VALUE)
        );
        DataBarangLayout.setVerticalGroup(
            DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );

        ContainerConten.add(DataBarang, "card2");

        DataSuplier.setBackground(new java.awt.Color(102, 0, 102));

        javax.swing.GroupLayout DataSuplierLayout = new javax.swing.GroupLayout(DataSuplier);
        DataSuplier.setLayout(DataSuplierLayout);
        DataSuplierLayout.setHorizontalGroup(
            DataSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1420, Short.MAX_VALUE)
        );
        DataSuplierLayout.setVerticalGroup(
            DataSuplierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );

        ContainerConten.add(DataSuplier, "card3");

        DataKategori.setBackground(new java.awt.Color(102, 102, 0));

        javax.swing.GroupLayout DataKategoriLayout = new javax.swing.GroupLayout(DataKategori);
        DataKategori.setLayout(DataKategoriLayout);
        DataKategoriLayout.setHorizontalGroup(
            DataKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1420, Short.MAX_VALUE)
        );
        DataKategoriLayout.setVerticalGroup(
            DataKategoriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 731, Short.MAX_VALUE)
        );

        ContainerConten.add(DataKategori, "card4");

        javax.swing.GroupLayout ManajemenDataLayout = new javax.swing.GroupLayout(ManajemenData);
        ManajemenData.setLayout(ManajemenDataLayout);
        ManajemenDataLayout.setHorizontalGroup(
            ManajemenDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ManajemenDataLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(ManajemenDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Navigasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ContainerConten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        ManajemenDataLayout.setVerticalGroup(
            ManajemenDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ManajemenDataLayout.createSequentialGroup()
                .addComponent(Navigasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(ContainerConten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        panel_tengah.add(ManajemenData, "card2");

        Laporan.setBackground(new java.awt.Color(255, 51, 51));
        Laporan.setPreferredSize(new java.awt.Dimension(1280, 699));

        javax.swing.GroupLayout LaporanLayout = new javax.swing.GroupLayout(Laporan);
        Laporan.setLayout(LaporanLayout);
        LaporanLayout.setHorizontalGroup(
            LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1420, Short.MAX_VALUE)
        );
        LaporanLayout.setVerticalGroup(
            LaporanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
        );

        panel_tengah.add(Laporan, "card4");

        Setting.setBackground(new java.awt.Color(51, 0, 255));

        javax.swing.GroupLayout SettingLayout = new javax.swing.GroupLayout(Setting);
        Setting.setLayout(SettingLayout);
        SettingLayout.setHorizontalGroup(
            SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1420, Short.MAX_VALUE)
        );
        SettingLayout.setVerticalGroup(
            SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
        );

        panel_tengah.add(Setting, "card5");

        transaksi.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout transaksiLayout = new javax.swing.GroupLayout(transaksi);
        transaksi.setLayout(transaksiLayout);
        transaksiLayout.setHorizontalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1420, Short.MAX_VALUE)
        );
        transaksiLayout.setVerticalGroup(
            transaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 906, Short.MAX_VALUE)
        );

        panel_tengah.add(transaksi, "card2");

        JPanelLogo.setPreferredSize(new java.awt.Dimension(108, 76));

        javax.swing.GroupLayout JPanelLogoLayout = new javax.swing.GroupLayout(JPanelLogo);
        JPanelLogo.setLayout(JPanelLogoLayout);
        JPanelLogoLayout.setHorizontalGroup(
            JPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 108, Short.MAX_VALUE)
        );
        JPanelLogoLayout.setVerticalGroup(
            JPanelLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 76, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelNavigasiBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_tengah, javax.swing.GroupLayout.DEFAULT_SIZE, 1420, Short.MAX_VALUE)
                    .addComponent(panel_atas, javax.swing.GroupLayout.DEFAULT_SIZE, 1420, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_atas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JPanelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_tengah, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)
                    .addComponent(panelNavigasiBar, javax.swing.GroupLayout.DEFAULT_SIZE, 906, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelNavigasiBarComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelNavigasiBarComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_panelNavigasiBarComponentMoved

    private void jLabelLogoTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLogoTransaksiMouseClicked
        // TODO add your handling code here:
        Utility.setSideBar(panel_tengah, transaksi);
    }//GEN-LAST:event_jLabelLogoTransaksiMouseClicked

    private void jLabelManajemenDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelManajemenDataMouseClicked
        // TODO add your handling code here:
        Utility.setSideBar(panel_tengah, ManajemenData);
    }//GEN-LAST:event_jLabelManajemenDataMouseClicked

    private void jLabelLaporanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelLaporanMouseClicked
        // TODO add your handling code here:
        Utility.setSideBar(panel_tengah, Laporan);
    }//GEN-LAST:event_jLabelLaporanMouseClicked

    private void jLabelUsesrsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelUsesrsMouseClicked
        // TODO add your handling code here:
        Utility.setSideBar(panel_tengah, Setting);
    }//GEN-LAST:event_jLabelUsesrsMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        Utility.setSideBar(ContainerConten, DataBarang);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        Utility.setSideBar(ContainerConten, DataSuplier);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        Utility.setSideBar(ContainerConten, DataKategori);
    }//GEN-LAST:event_jButton3MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ContainerConten;
    private javax.swing.JPanel DataBarang;
    private javax.swing.JPanel DataKategori;
    private javax.swing.JPanel DataSuplier;
    private javax.swing.JPanel JPanelLogo;
    private javax.swing.JLabel LabelJabatanUser;
    private javax.swing.JLabel LabelNamaToko;
    private javax.swing.JLabel LabelNamaUser;
    private javax.swing.JPanel Laporan;
    private javax.swing.JPanel ManajemenData;
    private javax.swing.JPanel Navigasi;
    private javax.swing.JPanel Setting;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelLaporan;
    private javax.swing.JLabel jLabelLogOut;
    private javax.swing.JLabel jLabelLogoTransaksi;
    private javax.swing.JLabel jLabelManajemenData;
    private javax.swing.JLabel jLabelUsesrs;
    private javax.swing.JPanel panelNavigasiBar;
    private javax.swing.JPanel panel_atas;
    private javax.swing.JPanel panel_tengah;
    private javax.swing.JPanel transaksi;
    // End of variables declaration//GEN-END:variables
}
