/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lafo;

/**
 *
 * @author mahmu
 */
public class MainJframe extends javax.swing.JFrame {

    /**
     * Creates new form Kasir
     */
    public MainJframe() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_atas = new javax.swing.JPanel();
        LabelNamaToko = new javax.swing.JLabel();
        LabelNamaUser = new javax.swing.JLabel();
        LabelJabatanUser = new javax.swing.JLabel();
        PanelFotoProfil = new javax.swing.JPanel();
        panelNavigasiBar = new javax.swing.JPanel();
        panelLogoTransaksi = new javax.swing.JPanel();
        PanelLogoManajemenData = new javax.swing.JPanel();
        PanelLogoLaporanToko = new javax.swing.JPanel();
        PanelLogoSetting = new javax.swing.JPanel();
        PanelLogoToko = new javax.swing.JPanel();
        panel_tengah = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        DataBarang = new javax.swing.JPanel();
        cardTotalBarang = new javax.swing.JPanel();
        JudulTotalBarang = new javax.swing.JLabel();
        ContainerLogoTotalBarang = new javax.swing.JPanel();
        TotalBarang = new javax.swing.JLabel();
        fieldPencarian = new javax.swing.JTextField();
        scroledPanelForTable = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labelShow = new javax.swing.JLabel();
        ComboBoxShowEntries = new javax.swing.JComboBox<>();
        LabelKategori = new javax.swing.JLabel();
        ComboBoxKategori = new javax.swing.JComboBox<>();
        LabelEntryes = new javax.swing.JLabel();
        ButtornTambah = new javax.swing.JButton();
        ButtonRetur = new javax.swing.JButton();
        ButtonRetur1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1, 982));

        panel_atas.setBackground(new java.awt.Color(241, 102, 52));
        panel_atas.setPreferredSize(new java.awt.Dimension(1280, 69));

        LabelNamaToko.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelNamaToko.setForeground(new java.awt.Color(255, 255, 255));
        LabelNamaToko.setText("CAFE LAFO");

        LabelNamaUser.setFont(new java.awt.Font("SansSerif", 1, 15)); // NOI18N
        LabelNamaUser.setForeground(new java.awt.Color(255, 255, 255));
        LabelNamaUser.setText("Dwi Nafis Mahardika");

        LabelJabatanUser.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        LabelJabatanUser.setForeground(new java.awt.Color(255, 255, 255));
        LabelJabatanUser.setText("Admin");

        PanelFotoProfil.setPreferredSize(new java.awt.Dimension(36, 36));

        javax.swing.GroupLayout PanelFotoProfilLayout = new javax.swing.GroupLayout(PanelFotoProfil);
        PanelFotoProfil.setLayout(PanelFotoProfilLayout);
        PanelFotoProfilLayout.setHorizontalGroup(
            PanelFotoProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );
        PanelFotoProfilLayout.setVerticalGroup(
            PanelFotoProfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 36, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panel_atasLayout = new javax.swing.GroupLayout(panel_atas);
        panel_atas.setLayout(panel_atasLayout);
        panel_atasLayout.setHorizontalGroup(
            panel_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_atasLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(LabelNamaToko)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 897, Short.MAX_VALUE)
                .addComponent(PanelFotoProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNamaUser)
                    .addComponent(LabelJabatanUser))
                .addGap(38, 38, 38))
        );
        panel_atasLayout.setVerticalGroup(
            panel_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_atasLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panel_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelFotoProfil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panel_atasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(panel_atasLayout.createSequentialGroup()
                            .addComponent(LabelNamaUser)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(LabelJabatanUser))
                        .addComponent(LabelNamaToko)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelNavigasiBar.setBackground(new java.awt.Color(42, 48, 48));
        panelNavigasiBar.setPreferredSize(new java.awt.Dimension(86, 699));
        panelNavigasiBar.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                panelNavigasiBarComponentMoved(evt);
            }
        });

        panelLogoTransaksi.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout panelLogoTransaksiLayout = new javax.swing.GroupLayout(panelLogoTransaksi);
        panelLogoTransaksi.setLayout(panelLogoTransaksiLayout);
        panelLogoTransaksiLayout.setHorizontalGroup(
            panelLogoTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        panelLogoTransaksiLayout.setVerticalGroup(
            panelLogoTransaksiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        PanelLogoManajemenData.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout PanelLogoManajemenDataLayout = new javax.swing.GroupLayout(PanelLogoManajemenData);
        PanelLogoManajemenData.setLayout(PanelLogoManajemenDataLayout);
        PanelLogoManajemenDataLayout.setHorizontalGroup(
            PanelLogoManajemenDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        PanelLogoManajemenDataLayout.setVerticalGroup(
            PanelLogoManajemenDataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        PanelLogoLaporanToko.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout PanelLogoLaporanTokoLayout = new javax.swing.GroupLayout(PanelLogoLaporanToko);
        PanelLogoLaporanToko.setLayout(PanelLogoLaporanTokoLayout);
        PanelLogoLaporanTokoLayout.setHorizontalGroup(
            PanelLogoLaporanTokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        PanelLogoLaporanTokoLayout.setVerticalGroup(
            PanelLogoLaporanTokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        PanelLogoSetting.setPreferredSize(new java.awt.Dimension(40, 40));

        javax.swing.GroupLayout PanelLogoSettingLayout = new javax.swing.GroupLayout(PanelLogoSetting);
        PanelLogoSetting.setLayout(PanelLogoSettingLayout);
        PanelLogoSettingLayout.setHorizontalGroup(
            PanelLogoSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );
        PanelLogoSettingLayout.setVerticalGroup(
            PanelLogoSettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelNavigasiBarLayout = new javax.swing.GroupLayout(panelNavigasiBar);
        panelNavigasiBar.setLayout(panelNavigasiBarLayout);
        panelNavigasiBarLayout.setHorizontalGroup(
            panelNavigasiBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavigasiBarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelNavigasiBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelLogoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelLogoManajemenData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelLogoLaporanToko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelLogoSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        panelNavigasiBarLayout.setVerticalGroup(
            panelNavigasiBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelNavigasiBarLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(panelLogoTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(PanelLogoManajemenData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(PanelLogoLaporanToko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(PanelLogoSetting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(424, Short.MAX_VALUE))
        );

        PanelLogoToko.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        PanelLogoToko.setPreferredSize(new java.awt.Dimension(50, 50));

        javax.swing.GroupLayout PanelLogoTokoLayout = new javax.swing.GroupLayout(PanelLogoToko);
        PanelLogoToko.setLayout(PanelLogoTokoLayout);
        PanelLogoTokoLayout.setHorizontalGroup(
            PanelLogoTokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        PanelLogoTokoLayout.setVerticalGroup(
            PanelLogoTokoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        panel_tengah.setPreferredSize(new java.awt.Dimension(1280, 699));
        panel_tengah.setLayout(new java.awt.CardLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(1416, 906));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1395, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 925, Short.MAX_VALUE)
        );

        panel_tengah.add(jPanel1, "card2");

        DataBarang.setBackground(new java.awt.Color(233, 235, 239));
        DataBarang.setForeground(java.awt.Color.white);
        DataBarang.setPreferredSize(new java.awt.Dimension(1410, 903));

        cardTotalBarang.setBackground(java.awt.Color.white);
        cardTotalBarang.setForeground(new java.awt.Color(255, 255, 255));
        cardTotalBarang.setPreferredSize(new java.awt.Dimension(191, 88));

        JudulTotalBarang.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        JudulTotalBarang.setText("Total Barang");
        JudulTotalBarang.setPreferredSize(new java.awt.Dimension(129, 22));

        ContainerLogoTotalBarang.setBackground(new java.awt.Color(255, 255, 255));
        ContainerLogoTotalBarang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ContainerLogoTotalBarang.setMinimumSize(new java.awt.Dimension(39, 39));

        javax.swing.GroupLayout ContainerLogoTotalBarangLayout = new javax.swing.GroupLayout(ContainerLogoTotalBarang);
        ContainerLogoTotalBarang.setLayout(ContainerLogoTotalBarangLayout);
        ContainerLogoTotalBarangLayout.setHorizontalGroup(
            ContainerLogoTotalBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        ContainerLogoTotalBarangLayout.setVerticalGroup(
            ContainerLogoTotalBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        TotalBarang.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        TotalBarang.setText("0");

        javax.swing.GroupLayout cardTotalBarangLayout = new javax.swing.GroupLayout(cardTotalBarang);
        cardTotalBarang.setLayout(cardTotalBarangLayout);
        cardTotalBarangLayout.setHorizontalGroup(
            cardTotalBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JudulTotalBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(cardTotalBarangLayout.createSequentialGroup()
                .addComponent(ContainerLogoTotalBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(TotalBarang))
        );
        cardTotalBarangLayout.setVerticalGroup(
            cardTotalBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cardTotalBarangLayout.createSequentialGroup()
                .addComponent(JudulTotalBarang, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(cardTotalBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cardTotalBarangLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ContainerLogoTotalBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(cardTotalBarangLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(TotalBarang)))
                .addGap(49, 49, 49))
        );

        fieldPencarian.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        fieldPencarian.setText("Cari Barang");
        fieldPencarian.setPreferredSize(new java.awt.Dimension(485, 51));

        scroledPanelForTable.setPreferredSize(new java.awt.Dimension(1375, 606));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        scroledPanelForTable.setViewportView(jTable1);

        labelShow.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        labelShow.setText("Show");

        ComboBoxShowEntries.setEditable(true);
        ComboBoxShowEntries.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        ComboBoxShowEntries.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "5", "10", "15", "20" }));
        ComboBoxShowEntries.setBorder(null);
        ComboBoxShowEntries.setPreferredSize(new java.awt.Dimension(76, 50));
        ComboBoxShowEntries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxShowEntriesActionPerformed(evt);
            }
        });

        LabelKategori.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        LabelKategori.setText("Kategori");

        ComboBoxKategori.setEditable(true);
        ComboBoxKategori.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        ComboBoxKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "makanan", "minuman" }));
        ComboBoxKategori.setBorder(null);
        ComboBoxKategori.setPreferredSize(new java.awt.Dimension(150, 50));
        ComboBoxKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxKategoriActionPerformed(evt);
            }
        });

        LabelEntryes.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        LabelEntryes.setText("Entries");

        ButtornTambah.setBackground(new java.awt.Color(241, 102, 52));
        ButtornTambah.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        ButtornTambah.setText("Tambah");
        ButtornTambah.setPreferredSize(new java.awt.Dimension(105, 49));

        ButtonRetur.setBackground(new java.awt.Color(241, 102, 52));
        ButtonRetur.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        ButtonRetur.setText("Retur");
        ButtonRetur.setPreferredSize(new java.awt.Dimension(105, 49));

        ButtonRetur1.setBackground(new java.awt.Color(159, 162, 171));
        ButtonRetur1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        ButtonRetur1.setText("Export");
        ButtonRetur1.setPreferredSize(new java.awt.Dimension(105, 49));
        ButtonRetur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRetur1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DataBarangLayout = new javax.swing.GroupLayout(DataBarang);
        DataBarang.setLayout(DataBarangLayout);
        DataBarangLayout.setHorizontalGroup(
            DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataBarangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DataBarangLayout.createSequentialGroup()
                        .addComponent(fieldPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelShow)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxShowEntries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelEntryes)
                        .addGap(14, 14, 14)
                        .addComponent(ComboBoxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(LabelKategori)
                        .addGap(18, 18, 18)
                        .addComponent(ButtornTambah, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ButtonRetur, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ButtonRetur1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scroledPanelForTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cardTotalBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DataBarangLayout.setVerticalGroup(
            DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DataBarangLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(cardTotalBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(DataBarangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelShow)
                    .addComponent(ComboBoxKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxShowEntries, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelKategori)
                    .addComponent(LabelEntryes)
                    .addComponent(ButtornTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonRetur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ButtonRetur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(scroledPanelForTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        panel_tengah.add(DataBarang, "card3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelNavigasiBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PanelLogoToko, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1416, 1416, 1416)
                        .addComponent(panel_tengah, javax.swing.GroupLayout.DEFAULT_SIZE, 1395, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panel_atas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_atas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(PanelLogoToko, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_tengah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(panelNavigasiBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 226, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void panelNavigasiBarComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelNavigasiBarComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_panelNavigasiBarComponentMoved

    private void ComboBoxShowEntriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxShowEntriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxShowEntriesActionPerformed

    private void ComboBoxKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxKategoriActionPerformed

    private void ButtonRetur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRetur1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonRetur1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonRetur;
    private javax.swing.JButton ButtonRetur1;
    private javax.swing.JButton ButtornTambah;
    private javax.swing.JComboBox<String> ComboBoxKategori;
    private javax.swing.JComboBox<String> ComboBoxShowEntries;
    private javax.swing.JPanel ContainerLogoTotalBarang;
    private javax.swing.JPanel DataBarang;
    private javax.swing.JLabel JudulTotalBarang;
    private javax.swing.JLabel LabelEntryes;
    private javax.swing.JLabel LabelJabatanUser;
    private javax.swing.JLabel LabelKategori;
    private javax.swing.JLabel LabelNamaToko;
    private javax.swing.JLabel LabelNamaUser;
    private javax.swing.JPanel PanelFotoProfil;
    private javax.swing.JPanel PanelLogoLaporanToko;
    private javax.swing.JPanel PanelLogoManajemenData;
    private javax.swing.JPanel PanelLogoSetting;
    private javax.swing.JPanel PanelLogoToko;
    private javax.swing.JLabel TotalBarang;
    private javax.swing.JPanel cardTotalBarang;
    private javax.swing.JTextField fieldPencarian;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel labelShow;
    private javax.swing.JPanel panelLogoTransaksi;
    private javax.swing.JPanel panelNavigasiBar;
    private javax.swing.JPanel panel_atas;
    private javax.swing.JPanel panel_tengah;
    private javax.swing.JScrollPane scroledPanelForTable;
    // End of variables declaration//GEN-END:variables
}
